/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hc.ihm;

import com.hc.Entites.Adresse;
import com.hc.Entites.Representant;
import com.hc.utils.Constantes.type_acces;
import com.hc.utils.GuiUtils;
import java.awt.Component;
import java.util.HashMap;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cflagollet
 */
public class JFrmIntLstRep extends javax.swing.JInternalFrame {

    private HashMap<Integer,Representant> hashRep;
    private type_acces typAcc;
    
    /**
     * Creates new form JFrmIntRep
     */
    public JFrmIntLstRep(HashMap<Integer,Representant> hashRep) {
        initComponents();
        this.hashRep = hashRep;
        remplitTable();
       
        typAcc = type_acces.visualisation;
        
        //on disable tous les composants du jPanel1
        GuiUtils.setEnableRec(jPanel1,false);

        jLblErreur.setVisible(false);

        jTblRep.getSelectionModel().addListSelectionListener(new SharedListSelectionHandler()); 
        jTblRep.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTxtNom = new javax.swing.JTextField();
        jTxtPrenom = new javax.swing.JTextField();
        jLblPrenom = new javax.swing.JLabel();
        jLblNom = new javax.swing.JLabel();
        jLblTxComm = new javax.swing.JLabel();
        jTxtTxComm = new javax.swing.JTextField();
        jBtnAnnuler = new javax.swing.JButton();
        jLblSalaire = new javax.swing.JLabel();
        jTxtSalaire = new javax.swing.JTextField();
        jBtnOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtNo = new javax.swing.JTextField();
        jLblErreur = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtAdrNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtAdrRue = new javax.swing.JTextField();
        jTxtAdrCP = new javax.swing.JTextField();
        jTxtAdrVille = new javax.swing.JTextField();
        jTxtAdrPays = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jBtnNouveau = new javax.swing.JButton();
        jBtnModifier = new javax.swing.JButton();
        jBtnSupprimer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblRep = new javax.swing.JTable();

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setTitle("Liste des représentants");
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(906, 500));
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, -1, 702));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        setClosable(true);
        setMaximizable(true);
        setTitle("Liste des représentants");
        setPreferredSize(new java.awt.Dimension(906, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, -1, 702));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxtNom.setInputVerifier(new verifyTxtFieldString());
        jTxtNom.setNextFocusableComponent(jTxtPrenom);
        jPanel1.add(jTxtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 170, -1));

        jTxtPrenom.setInputVerifier(new verifyTxtFieldString());
        jTxtPrenom.setNextFocusableComponent(jTxtTxComm);
        jPanel1.add(jTxtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 170, -1));

        jLblPrenom.setText("Prénom");
        jPanel1.add(jLblPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 57, 20));

        jLblNom.setText("Nom");
        jPanel1.add(jLblNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 20));

        jLblTxComm.setText("Taux de commission");
        jPanel1.add(jLblTxComm, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 183, -1, 0));

        jTxtTxComm.setInputVerifier(new verifyTxtFieldNumber());
        jTxtTxComm.setNextFocusableComponent(jTxtSalaire);
        jTxtTxComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTxCommActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtTxComm, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 40, -1));

        jBtnAnnuler.setText("Annuler");
        jBtnAnnuler.setToolTipText("");
        jBtnAnnuler.setNextFocusableComponent(jTxtNom);
        jBtnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        jLblSalaire.setText("Salaire");
        jPanel1.add(jLblSalaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        jTxtSalaire.setToolTipText("");
        jTxtSalaire.setAutoscrolls(false);
        jTxtSalaire.setInputVerifier(new verifyTxtFieldNumber());
        jTxtSalaire.setNextFocusableComponent(jTxtAdrNo);
        jPanel1.add(jTxtSalaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 70, -1));

        jBtnOK.setText("OK");
        jBtnOK.setNextFocusableComponent(jBtnAnnuler);
        jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOKActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabel1.setText("Taux");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 20));

        jTxtNo.setEditable(false);
        jTxtNo.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jTxtNo.setEnabled(false);
        jTxtNo.setFocusable(false);
        jTxtNo.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jTxtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        jLblErreur.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLblErreur.setForeground(new java.awt.Color(255, 51, 0));
        jLblErreur.setText("Veuillez vérifier votre saisie !");
        jLblErreur.setEnabled(false);
        jLblErreur.setFocusable(false);
        jLblErreur.setRequestFocusEnabled(false);
        jLblErreur.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLblErreur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 170, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Adresse"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Numéro");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 57, -1));

        jTxtAdrNo.setInputVerifier(new verifyTxtFieldInt());
        jTxtAdrNo.setNextFocusableComponent(jTxtAdrRue);
        jPanel5.add(jTxtAdrNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 40, -1));

        jLabel4.setText("Rue");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 57, 10));

        jTxtAdrRue.setInputVerifier(new verifyTxtFieldString());
        jTxtAdrRue.setNextFocusableComponent(jTxtAdrCP);
        jPanel5.add(jTxtAdrRue, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 210, -1));

        jTxtAdrCP.setInputVerifier(new verifyTxtFieldInt());
        jTxtAdrCP.setNextFocusableComponent(jTxtAdrVille);
        jTxtAdrCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAdrCPActionPerformed(evt);
            }
        });
        jPanel5.add(jTxtAdrCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 60, -1));

        jTxtAdrVille.setInputVerifier(new verifyTxtFieldString());
        jTxtAdrVille.setNextFocusableComponent(jTxtAdrPays);
        jPanel5.add(jTxtAdrVille, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 160, -1));

        jTxtAdrPays.setInputVerifier(new verifyTxtFieldString());
        jTxtAdrPays.setNextFocusableComponent(jBtnOK);
        jPanel5.add(jTxtAdrPays, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 160, -1));

        jLabel5.setText("Code postal");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 10));

        jLabel6.setText("Ville");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 20));

        jLabel7.setText("Pays");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 20));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 330, 200));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        jBtnNouveau.setText("Nouveau");
        jBtnNouveau.setFocusPainted(false);
        jBtnNouveau.setFocusable(false);
        jBtnNouveau.setName("jBtnNouveau"); // NOI18N
        jBtnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNouveauModifierActionPerformed(evt);
            }
        });

        jBtnModifier.setText("Modifier");
        jBtnModifier.setEnabled(false);
        jBtnModifier.setFocusable(false);
        jBtnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNouveauModifierActionPerformed(evt);
            }
        });

        jBtnSupprimer.setText("Supprimer");
        jBtnSupprimer.setEnabled(false);
        jBtnSupprimer.setFocusable(false);
        jBtnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnNouveau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jBtnNouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 0, -1, 120));

        jTblRep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N°", "Nom", "Prénom", "Adresse", "Taux", "Salaire"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblRep.setFocusable(false);
        jScrollPane2.setViewportView(jTblRep);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 727, 173));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Listener pour les boutons Création et Modification
    private void jBtnNouveauModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNouveauModifierActionPerformed
        //Clic sur Modifier
        if (evt.getSource().equals((Object) jBtnModifier))  {
            typAcc = type_acces.modification;
        } else {
            remplitFiche(-1); //vide la fiche 
            typAcc = type_acces.creation;
        }
        
        //Liste et boutons du haut grisés
        GuiUtils.setEnableRec(jPanel4, false);
        GuiUtils.setEnableRec(jTblRep,false);
        
        GuiUtils.setEnableRec(jPanel1,true);  //fiche enabled
        jTxtNo.setEnabled(false);             //Numéro non modifiable
        jTxtNom.requestFocusInWindow();       //Focus sur le nom
    }//GEN-LAST:event_jBtnNouveauModifierActionPerformed

    private void jTxtAdrCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAdrCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAdrCPActionPerformed

    private void jBtnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnnulerActionPerformed
        jTblRep.clearSelection();
        remplitFiche(-1);
        GuiUtils.setEnableRec(jPanel1,false);
        GuiUtils.setEnableRec(jPanel4, true);
        GuiUtils.setEnableRec(jTblRep,true);
        jBtnModifier.setEnabled(false);
        jBtnSupprimer.setEnabled(false);
        jLblErreur.setVisible(false);
        typAcc = type_acces.visualisation;
    }//GEN-LAST:event_jBtnAnnulerActionPerformed

    private void jBtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOKActionPerformed

        if (verifyFields(jPanel1)) {
            jLblErreur.setVisible(false);
            sauveFiche();
            typAcc = type_acces.visualisation;
            GuiUtils.setEnableRec(jPanel4, true);
            GuiUtils.setEnableRec(jTblRep,true);
            jBtnModifier.setEnabled(false);
            jBtnSupprimer.setEnabled(false);
        }
        
    }//GEN-LAST:event_jBtnOKActionPerformed

    private void jBtnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSupprimerActionPerformed
        if (typAcc != type_acces.visualisation)
            if (JOptionPane.showConfirmDialog(null,"Etes-vous sûr de vouloir abandonner vos modifications ?","Attention",JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) 
                return;
        supprimeFiche();

    }//GEN-LAST:event_jBtnSupprimerActionPerformed

    private void jTxtTxCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTxCommActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTxCommActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAnnuler;
    private javax.swing.JButton jBtnModifier;
    private javax.swing.JButton jBtnNouveau;
    private javax.swing.JButton jBtnOK;
    private javax.swing.JButton jBtnSupprimer;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLblErreur;
    private javax.swing.JLabel jLblNom;
    private javax.swing.JLabel jLblPrenom;
    private javax.swing.JLabel jLblSalaire;
    private javax.swing.JLabel jLblTxComm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblRep;
    private javax.swing.JTextField jTxtAdrCP;
    private javax.swing.JTextField jTxtAdrNo;
    private javax.swing.JTextField jTxtAdrPays;
    private javax.swing.JTextField jTxtAdrRue;
    private javax.swing.JTextField jTxtAdrVille;
    private javax.swing.JTextField jTxtNo;
    private javax.swing.JTextField jTxtNom;
    private javax.swing.JTextField jTxtPrenom;
    private javax.swing.JTextField jTxtSalaire;
    private javax.swing.JTextField jTxtTxComm;
    // End of variables declaration//GEN-END:variables

    private void remplitTable()
    {
        String [] cols = {"No","Nom","Prenom","Adresse","Salaire","Taux"}; 
        DefaultTableModel listData = new DefaultTableModel(cols,0); 
        
        for (Representant r : hashRep.values()) {
            String[] ts = {Integer.toString(r.getNo()),
                r.getNom(),
                r.getPrenom(),
                r.getAdrToString(),
                Double.toString(r.getSalaire()),
                Double.toString(r.getTxComm())};
            
         listData.addRow(ts);
        }

        jTblRep.setModel(listData);
        initTailleCols();
    }

    //Taille des colonnes
    private void initTailleCols() 
    {
        int[] tailleCol = {37,118,92,307,84,83};
        for (int i=0;i<tailleCol.length;i++)
            jTblRep.getColumnModel().getColumn(i).setPreferredWidth(tailleCol[i]);       
    }
    
    
    private void remplitFiche(int noRep) 
    {
        if (noRep != -1) {
        Representant r = hashRep.get(noRep);

        jTxtNom.setText(r.getNom());
        jTxtPrenom.setText(r.getPrenom());
        jTxtTxComm.setText(String.valueOf(r.getTxComm()));
        jTxtSalaire.setText(String.valueOf(r.getSalaire()));
        jTxtAdrNo.setText(String.valueOf(r.getAdresse().getNo()));
        jTxtAdrRue.setText(r.getAdresse().getRue());
        jTxtAdrVille.setText(r.getAdresse().getVille());
        jTxtAdrCP.setText(String.valueOf(r.getAdresse().getCp()));
        jTxtAdrPays.setText(r.getAdresse().getPays());
        jTxtNo.setText(String.valueOf(r.getNo()));
        } else {
            jTxtNom.setText("");
            jTxtPrenom.setText("");
            jTxtTxComm.setText("");
            jTxtSalaire.setText("");
            jTxtAdrNo.setText("");
            jTxtAdrRue.setText("");
            jTxtAdrVille.setText("");
            jTxtAdrCP.setText("");
            jTxtAdrPays.setText("");
            jTxtNo.setText("");
        }
            
        jLblErreur.setVisible(false);
    }
    
    private void sauveFiche()
    { 
        if (typAcc == type_acces.modification) {
            Representant r = new Representant(  Integer.parseInt(jTxtNo.getText()),
                                                Double.parseDouble(jTxtTxComm.getText()),
                                                Double.parseDouble(jTxtSalaire.getText()),
                                                jTxtNom.getText(),
                                                jTxtPrenom.getText(),
                                                new Adresse(Integer.parseInt(jTxtAdrNo.getText()), 
                                                            jTxtAdrRue.getText(),
                                                            Integer.parseInt(jTxtAdrCP.getText()),
                                                            jTxtAdrVille.getText(),
                                                            jTxtAdrPays.getText()));

                    // Representant(int no, double txComm, double salaire, String nom, String prenom, Adresse adresse)
            hashRep.put(Integer.parseInt(jTxtNo.getText()),r);
        } else {
            Representant r = new Representant(  Double.parseDouble(jTxtTxComm.getText()),
                                                Double.parseDouble(jTxtSalaire.getText()),
                                                jTxtNom.getText(),
                                                jTxtPrenom.getText(),
                                                new Adresse(Integer.parseInt(jTxtAdrNo.getText()), 
                                                            jTxtAdrRue.getText(),
                                                            Integer.parseInt(jTxtAdrCP.getText()),
                                                            jTxtAdrVille.getText(),
                                                            jTxtAdrPays.getText()));
            hashRep.put(Representant.getDernierNo(),r);
        }
        

    }
        
    private void supprimeFiche() {

        //Verification de l'intégrité des données (on ne peut pas supprimer un représentant s'il est utilisé ailleurs (client ou prospect)
        if (verifIntegriteRep()) {
            //Affichage boite de dialogue pour confirmation
            if (JOptionPane.showConfirmDialog(null,"Etes-vous sûr de vouloir supprimer ce représentant ?","Attention",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                Representant r = hashRep.get(Integer.parseInt(jTxtNo.getText()));
                hashRep.remove(Integer.parseInt(jTxtNo.getText()),r);
                //On vide tout
                jTblRep.clearSelection();
                remplitFiche(-1);
                //Affichage nouvelle liste
                remplitTable(); 
                typAcc = type_acces.visualisation;
        
            }
        } else { // Sinon, on affiche un message d'alerte
            
        }
                
    }
    
    //Verification de l'intégrité des données 
    private boolean verifIntegriteRep()
    {
        return true;
    }
    
    private boolean  verifyFields(Component container) 
    {    
       //ne fonctionne pas donc fait à la main pour l'instant
        /*
        
            Component[] components= ((Container) container).getComponents();
            for (Component c : components) {
                                System.out.println("je controle " + c.getName());
              try {                  
                if (c instanceof JTextField) {
                    if (!getInputVerifier().verify((JComponent) c)) {
                        System.out.println("ça chie dans la colle pour : " + c.getName());
                        return false ;
                    }
                }
              } catch (ClassCastException e) {
                //TODO : gestion exception
              }
            }
     */
        //TODO : à refaire avec une boucle sur les composants
        if (!new verifyTxtFieldString().verify(jTxtNom)) return false ;
        if (!new verifyTxtFieldString().verify(jTxtPrenom)) return false ;
        if (!new verifyTxtFieldString().verify(jTxtAdrRue)) return false ;
        if (!new verifyTxtFieldString().verify(jTxtAdrVille)) return false ;
        if (!new verifyTxtFieldString().verify(jTxtAdrPays)) return false ;
        if (!new verifyTxtFieldInt().verify(jTxtAdrCP)) return false ;
        if (!new verifyTxtFieldInt().verify(jTxtAdrNo)) return false ;
        if (!new verifyTxtFieldNumber().verify(jTxtSalaire)) return false ;
        if (!new verifyTxtFieldNumber().verify(jTxtTxComm)) return false ;
        
        return true;        
        
    }
    
    class SharedListSelectionHandler implements ListSelectionListener {
        @Override
        public void valueChanged(ListSelectionEvent e) { 
            ListSelectionModel lsm = (ListSelectionModel)e.getSource();
            
            GuiUtils.setEnableRec(jPanel1,false);
            
            if (lsm.isSelectionEmpty()) {
                jBtnModifier.setEnabled(false);
                jBtnSupprimer.setEnabled(false);
            }
            else {
                /* TODO Revoir cette partie
                if (typAcc != type_acces.visualisation) {
                     if (JOptionPane.showConfirmDialog(null,"Etes-vous sûr de vouloir abandonner vos modifications ?","Attention",JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) 
                        lsm.clearSelection();
                        return;
                }*/
                    
                int noRep = Integer.parseInt(jTblRep.getModel().getValueAt(jTblRep.getSelectedRow(),0).toString());
                remplitFiche(noRep);
                jBtnModifier.setEnabled(true);
                jBtnSupprimer.setEnabled(true);                
            }
        }
                
    }
    
    class verifyTxtFieldString extends InputVerifier {
         @Override
         public boolean verify(JComponent input) {
             JTextField tf = (JTextField) input;
             boolean bOk = !tf.getText().isEmpty();
     //        jLblErreur.setLocation(tf.getLocation().x,tf.getLocation().y+230);
     //        jLblErreur.paint(tf.getGraphics());
             jLblErreur.setVisible(!bOk);


             return (bOk);
         }
    }
    
    class verifyTxtFieldInt extends InputVerifier {
         @Override
         public boolean verify(JComponent input) {
             boolean bOk = true;
             JTextField tf = (JTextField) input;
             try {
                 int i = Integer.parseInt(tf.getText());                 
             }
             catch (Exception e) {
                 bOk = false;
             }
             jLblErreur.setVisible(!bOk);
             return bOk;
         }
    }

    class verifyTxtFieldNumber extends InputVerifier {
         @Override
        public boolean verify(JComponent input) {
            boolean bOk = true;
            JTextField tf = (JTextField) input;
            try {
                double d = Double.parseDouble(tf.getText());                 
            }
            catch (Exception e) {
                bOk = false;
            }
            jLblErreur.setVisible(!bOk);
            return bOk;
        }
   }
    
    
    
    //TODO : verifier que le champ taux <100
    //TODO : vérifier que le champ CP 5 chiffres
    
}
