/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hc.ihm;

import com.hc.Entites.Adresse;
import com.hc.Entites.Produit;
import com.hc.Entites.Prospect;
import com.hc.Entites.Representant;
import com.hc.utils.Constantes.type_acces;
import com.hc.utils.GuiUtils;
import java.awt.Component;
import java.util.HashMap;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cflagollet
 */
public class JFrmIntLstProduit extends javax.swing.JInternalFrame {

    private HashMap<String,Produit> hashProduit;
    private type_acces typAcc;
    
    /**
     * Creates new form JFrmIntRep
     */
    public JFrmIntLstProduit(HashMap<String,Produit> hashProduit) {
        this.hashProduit = hashProduit;
        initComponents();
        remplitTable();
        typAcc = type_acces.visualisation; //par défaut en visu
        
        //on disable tous les composants du jPanel1
        GuiUtils.setEnableRec(jPanel1,false);
        jLblErreur.setVisible(false);
        
        typAcc = type_acces.visualisation;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTxtDésignation = new javax.swing.JTextField();
        jTxtPrixHT = new javax.swing.JTextField();
        jLblDesignation = new javax.swing.JLabel();
        jLblCode = new javax.swing.JLabel();
        jLblTxComm = new javax.swing.JLabel();
        jTxtQuantite = new javax.swing.JTextField();
        jBtnAnnuler = new javax.swing.JButton();
        jLblQuantite = new javax.swing.JLabel();
        jBtnOK = new javax.swing.JButton();
        jLblPrixHT = new javax.swing.JLabel();
        jTxtCode = new javax.swing.JTextField();
        jLblErreur = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jBtnNouveau = new javax.swing.JButton();
        jBtnModifier = new javax.swing.JButton();
        jBtnSupprimer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblRep = new javax.swing.JTable();
        jLblFiltre = new javax.swing.JLabel();

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setTitle("Liste des représentants");
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(906, 500));
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, -1, 702));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jInternalFrame1.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        setClosable(true);
        setMaximizable(true);
        setTitle("Gestion des produits");
        setPreferredSize(new java.awt.Dimension(906, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, -1, 702));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxtDésignation.setInputVerifier(new verifyTxtFieldString());
        jTxtDésignation.setNextFocusableComponent(jTxtPrixHT);
        jPanel1.add(jTxtDésignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 390, -1));

        jTxtPrixHT.setInputVerifier(new verifyTxtFieldString());
        jTxtPrixHT.setNextFocusableComponent(jTxtQuantite);
        jPanel1.add(jTxtPrixHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 60, -1));

        jLblDesignation.setText("Désignation");
        jPanel1.add(jLblDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 57, 20));

        jLblCode.setText("Code ");
        jPanel1.add(jLblCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 20));

        jLblTxComm.setText("Taux de commission");
        jPanel1.add(jLblTxComm, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 183, -1, 0));

        jTxtQuantite.setInputVerifier(new verifyTxtFieldDouble());
        jTxtQuantite.setNextFocusableComponent(jBtnOK);
        jPanel1.add(jTxtQuantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 40, -1));

        jBtnAnnuler.setText("Annuler");
        jBtnAnnuler.setToolTipText("");
        jBtnAnnuler.setNextFocusableComponent(jTxtDésignation);
        jBtnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLblQuantite.setText("Quantité");
        jPanel1.add(jLblQuantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 20));

        jBtnOK.setText("OK");
        jBtnOK.setNextFocusableComponent(jBtnAnnuler);
        jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOKActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        jLblPrixHT.setText("Prix HT");
        jPanel1.add(jLblPrixHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, 20));

        jTxtCode.setEditable(false);
        jTxtCode.setBackground(new java.awt.Color(255, 255, 255));
        jTxtCode.setEnabled(false);
        jTxtCode.setFocusCycleRoot(true);
        jTxtCode.setNextFocusableComponent(jTxtDésignation);
        jTxtCode.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jTxtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 60, -1));

        jLblErreur.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLblErreur.setForeground(new java.awt.Color(255, 51, 0));
        jLblErreur.setText("Veuillez vérifier votre saisie !");
        jLblErreur.setEnabled(false);
        jLblErreur.setFocusable(false);
        jLblErreur.setRequestFocusEnabled(false);
        jLblErreur.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLblErreur, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 170, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        jBtnNouveau.setText("Nouveau");
        jBtnNouveau.setFocusPainted(false);
        jBtnNouveau.setFocusable(false);
        jBtnNouveau.setName("jBtnNouveau"); // NOI18N
        jBtnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNouveauModifierActionPerformed(evt);
            }
        });

        jBtnModifier.setText("Modifier");
        jBtnModifier.setEnabled(false);
        jBtnModifier.setFocusable(false);
        jBtnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNouveauModifierActionPerformed(evt);
            }
        });

        jBtnSupprimer.setText("Supprimer");
        jBtnSupprimer.setEnabled(false);
        jBtnSupprimer.setFocusable(false);
        jBtnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnNouveau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jBtnNouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 0, -1, 120));

        jTblRep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblRep.setFocusable(false);
        jScrollPane2.setViewportView(jTblRep);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 727, 173));

        jLblFiltre.setText("Filtre : ");
        getContentPane().add(jLblFiltre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Listener pour les boutons Création et Modification
    private void jBtnNouveauModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNouveauModifierActionPerformed
        //Clic sur Modifier
        if (evt.getSource().equals((Object) jBtnModifier))  {
            typAcc = type_acces.modification;
        } else {
            remplitFiche(""); //vide la fiche 
            typAcc = type_acces.creation;
        }
        
        //Liste et boutons du haut grisés
        GuiUtils.setEnableRec(jPanel4, false);
        GuiUtils.setEnableRec(jTblRep,false);
        GuiUtils.setEnableRec(jPanel1,true);  //fiche enabled
        jTxtCode.setEnabled(false);             //Numéro non modifiable
        jTxtDésignation.requestFocusInWindow();       //Focus sur le nom
    }//GEN-LAST:event_jBtnNouveauModifierActionPerformed

    private void jBtnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnnulerActionPerformed
        jTblRep.clearSelection();
        remplitFiche("");
        GuiUtils.setEnableRec(jPanel1,false);
        GuiUtils.setEnableRec(jPanel4, true);
        GuiUtils.setEnableRec(jTblRep,true);
        jBtnModifier.setEnabled(false);
        jBtnSupprimer.setEnabled(false);
        jLblErreur.setVisible(false);
        typAcc = type_acces.visualisation;
    }//GEN-LAST:event_jBtnAnnulerActionPerformed

    private void jBtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOKActionPerformed

        if (verifyFields(jPanel1)) {
            jLblErreur.setVisible(false);
            sauveFiche();
            typAcc = type_acces.visualisation;
            GuiUtils.setEnableRec(jPanel4, true);
            GuiUtils.setEnableRec(jTblRep,true);
            jBtnModifier.setEnabled(false);
            jBtnSupprimer.setEnabled(false);
        }
        
    }//GEN-LAST:event_jBtnOKActionPerformed

    private void jBtnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSupprimerActionPerformed
   /*     if (typAcc != type_acces.visualisation)
            if (JOptionPane.showConfirmDialog(null,"Etes-vous sûr de vouloir abandonner vos modifications ?","Attention",JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) 
                return; */
        supprimeFiche();

    }//GEN-LAST:event_jBtnSupprimerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAnnuler;
    private javax.swing.JButton jBtnModifier;
    private javax.swing.JButton jBtnNouveau;
    private javax.swing.JButton jBtnOK;
    private javax.swing.JButton jBtnSupprimer;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLblCode;
    private javax.swing.JLabel jLblDesignation;
    private javax.swing.JLabel jLblErreur;
    private javax.swing.JLabel jLblFiltre;
    private javax.swing.JLabel jLblPrixHT;
    private javax.swing.JLabel jLblQuantite;
    private javax.swing.JLabel jLblTxComm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblRep;
    private javax.swing.JTextField jTxtCode;
    private javax.swing.JTextField jTxtDésignation;
    private javax.swing.JTextField jTxtPrixHT;
    private javax.swing.JTextField jTxtQuantite;
    // End of variables declaration//GEN-END:variables

    private void remplitTable()
    {
        String [] cols = {"Code","Désignation","Prix HT","Quantité stock"}; 
        DefaultTableModel listData = new DefaultTableModel(cols,0); 
        
        for (Produit r : hashProduit.values()) {
            String[] ts = {r.getCode(),
                r.getDesignation(),
                Double.toString(r.getPrixHT()),
                Integer.toString(r.getQteStock())};
            
            listData.addRow(ts);
        }

        jTblRep.setModel(listData);
        initTailleCols();
    }

    //Taille des colonnes
    private void initTailleCols() 
    {
        int[] tailleCol = {37,240,42,100};
        for (int i=0;i<tailleCol.length;i++)
            jTblRep.getColumnModel().getColumn(i).setPreferredWidth(tailleCol[i]);       
    }
    
    
    private void remplitFiche(String code) 
    {
        if (!code.isEmpty()) {
        Produit p = hashProduit.get(code);

        jTxtDésignation.setText(p.getDesignation());
        jTxtPrixHT.setText(String.valueOf(p.getPrixHT()));
        jTxtQuantite.setText(String.valueOf(p.getQteStock()));
        jTxtCode.setText(p.getCode());
        } else {
            jTxtDésignation.setText("");
            jTxtPrixHT.setText("");
            jTxtQuantite.setText("");
            jTxtCode.setText("");
        }
            
        jLblErreur.setVisible(false);
    }
    
    private void sauveFiche()
    { 
        if (typAcc == type_acces.modification) {
            Produit p = new Produit(   jTxtCode.getText(),
                                       jTxtDésignation.getText(),
                                       Double.parseDouble(jTxtPrixHT.getText()),    
                                       Integer.parseInt(jTxtQuantite.getText()));
                      
            hashProduit.put(jTxtCode.getText(),p);
           
        } else {
            Produit p = new Produit(   jTxtDésignation.getText(),
                                       Double.parseDouble(jTxtPrixHT.getText()),
                                       Integer.parseInt(jTxtQuantite.getText()));
                                                
            hashProduit.put("IND",p); //
        }
        

    }
        
    private void supprimeFiche() {

        //Verification de l'intégrité des données (on ne peut pas supprimer un représentant s'il est utilisé ailleurs (client ou prospect)
        if (verifIntegriteRep()) {
            //Affichage boite de dialogue pour confirmation
            if (JOptionPane.showConfirmDialog(null,"Etes-vous sûr de vouloir supprimer ce représentant ?","Attention",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                Produit r = hashProduit.get(Integer.parseInt(jTxtCode.getText()));
                hashProduit.remove(Integer.parseInt(jTxtCode.getText()),r);
                //On vide tout
                jTblRep.clearSelection();
                remplitFiche("");
                //Affichage nouvelle liste
                remplitTable(); 
                typAcc = type_acces.visualisation;
        
            }
        } else { // Sinon, on affiche un message d'alerte
            
        }
                
    }
    
    //Verification de l'intégrité des données 
    private boolean verifIntegriteRep()
    {
        return true;
    }
    
    private boolean  verifyFields(Component container) 
    {    
       //ne fonctionne pas donc fait à la main pour l'instant
        /*
        
            Component[] components= ((Container) container).getComponents();
            for (Component c : components) {
                                System.out.println("je controle " + c.getName());
              try {                  
                if (c instanceof JTextField) {
                    if (!getInputVerifier().verify((JComponent) c)) {
                        System.out.println("ça chie dans la colle pour : " + c.getName());
                        return false ;
                    }
                }
              } catch (ClassCastException e) {
                //TODO : gestion exception
              }
            }
     */
        //TODO : à refaire avec une boucle sur les composants
        if (!new verifyTxtFieldString().verify(jTxtDésignation)) return false ;
        if (!new verifyTxtFieldDouble().verify(jTxtPrixHT)) return false ;
        if (!new verifyTxtFieldInt().verify(jTxtQuantite)) return false ;
        
        return true;        
        
    }
    
    class SharedListSelectionHandler implements ListSelectionListener {
        @Override
        public void valueChanged(ListSelectionEvent e) { 
            ListSelectionModel lsm = (ListSelectionModel)e.getSource();
            
            GuiUtils.setEnableRec(jPanel1,false);
            
            if (lsm.isSelectionEmpty()) {
                jBtnModifier.setEnabled(false);
                jBtnSupprimer.setEnabled(false);
            }
            else {
                /* TODO Revoir cette partie
                if (typAcc != type_acces.visualisation) {
                     if (JOptionPane.showConfirmDialog(null,"Etes-vous sûr de vouloir abandonner vos modifications ?","Attention",JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) 
                        lsm.clearSelection();
                        return;
                }*/
                    
                String code = jTblRep.getModel().getValueAt(jTblRep.getSelectedRow(),0).toString();
                remplitFiche(code);
                jBtnModifier.setEnabled(true);
                jBtnSupprimer.setEnabled(true);                
            }
        }
                
    }
    
    class verifyTxtFieldString extends InputVerifier {
         @Override
         public boolean verify(JComponent input) {
             JTextField tf = (JTextField) input;
             boolean bOk = !tf.getText().isEmpty();
     //        jLblErreur.setLocation(tf.getLocation().x,tf.getLocation().y+230);
     //        jLblErreur.paint(tf.getGraphics());
             jLblErreur.setVisible(!bOk);


             return (bOk);
         }
    }
    
    class verifyTxtFieldInt extends InputVerifier {
         @Override
         public boolean verify(JComponent input) {
             boolean bOk = true;
             JTextField tf = (JTextField) input;
             try {
                 int i = Integer.parseInt(tf.getText()); 
                 if (i<=0)
                     bOk=false;
             }
             catch (Exception e) {
                 bOk = false;
             }
             jLblErreur.setVisible(!bOk);
             return bOk;
         }
    }

    class verifyTxtFieldDouble extends InputVerifier {
         @Override
        public boolean verify(JComponent input) {
            boolean bOk = true;
            JTextField tf = (JTextField) input;
            try {
                double d = Double.parseDouble(tf.getText());                 
                if (d<=0) 
                    bOk=false;
            }
            catch (Exception e) {
                bOk = false;
            }
            jLblErreur.setVisible(!bOk);
            return bOk;
        }
   }
    
    
    
    //TODO : verifier que le champ taux <100
    //TODO : vérifier que le champ CP 5 chiffres
    
}
